"""add reminder lead time preference and student reminder tracking

Revision ID: 41847be334d7
Revises: afc6a11a104d
Create Date: 2026-08-08 08:09:23.663348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41847be334d7'
down_revision: Union[str, None] = 'afc6a11a104d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('bookings', sa.Column('student_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reminder_lead_minutes', sa.Integer(), nullable=False, server_default='60'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_lead_minutes')
    op.drop_column('bookings', 'student_reminder_sent_at')
    # ### end Alembic commands ###
