"""add system notifications and notification templates

Revision ID: 812624be4c19
Revises: d757ed331323
Create Date: 2026-08-07 14:41:14.782430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812624be4c19'
down_revision: Union[str, None] = 'd757ed331323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'role', name='uq_notification_template_event_role')
    )
    op.create_table('system_notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_notifications_created_at'), 'system_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_notifications_user_id'), 'system_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_notifications_user_id'), table_name='system_notifications')
    op.drop_index(op.f('ix_system_notifications_created_at'), table_name='system_notifications')
    op.drop_table('system_notifications')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
