"""add first_name last_name patronymic to users

Revision ID: 865d282e4db9
Revises: 8c423cc12276
Create Date: 2026-07-16 23:07:12.662618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865d282e4db9'
down_revision: Union[str, None] = '8c423cc12276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), server_default='', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), server_default='', nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
