"""add subjects/directions, drop tutor_profiles.prepares_for

Revision ID: afaef8f1e8f1
Revises: 865d282e4db9
Create Date: 2026-07-17 23:16:50.197834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afaef8f1e8f1'
down_revision: Union[str, None] = '865d282e4db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('directions',
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'name', name='uq_direction_subject_name')
    )
    op.create_index(op.f('ix_directions_subject_id'), 'directions', ['subject_id'], unique=False)
    op.create_table('tutor_subjects',
    sa.Column('tutor_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id', 'subject_id', name='uq_tutor_subject')
    )
    op.create_index(op.f('ix_tutor_subjects_subject_id'), 'tutor_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_tutor_subjects_tutor_id'), 'tutor_subjects', ['tutor_id'], unique=False)
    op.create_table('tutor_subject_directions',
    sa.Column('tutor_subject_id', sa.Uuid(), nullable=False),
    sa.Column('direction_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutor_subject_id'], ['tutor_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_subject_id', 'direction_id', name='uq_tutor_subject_direction')
    )
    op.create_index(op.f('ix_tutor_subject_directions_direction_id'), 'tutor_subject_directions', ['direction_id'], unique=False)
    op.create_index(op.f('ix_tutor_subject_directions_tutor_subject_id'), 'tutor_subject_directions', ['tutor_subject_id'], unique=False)
    op.drop_column('tutor_profiles', 'prepares_for')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_profiles', sa.Column('prepares_for', sa.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_tutor_subject_directions_tutor_subject_id'), table_name='tutor_subject_directions')
    op.drop_index(op.f('ix_tutor_subject_directions_direction_id'), table_name='tutor_subject_directions')
    op.drop_table('tutor_subject_directions')
    op.drop_index(op.f('ix_tutor_subjects_tutor_id'), table_name='tutor_subjects')
    op.drop_index(op.f('ix_tutor_subjects_subject_id'), table_name='tutor_subjects')
    op.drop_table('tutor_subjects')
    op.drop_index(op.f('ix_directions_subject_id'), table_name='directions')
    op.drop_table('directions')
    op.drop_table('subjects')
    # ### end Alembic commands ###
