"""add chat_thread_reads table

Revision ID: d757ed331323
Revises: a0bec54900f1
Create Date: 2026-08-04 17:44:09.506115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd757ed331323'
down_revision: Union[str, None] = 'a0bec54900f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_thread_reads',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_chat_thread_read')
    )
    op.create_index(op.f('ix_chat_thread_reads_thread_id'), 'chat_thread_reads', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_thread_reads_user_id'), 'chat_thread_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_thread_reads_user_id'), table_name='chat_thread_reads')
    op.drop_index(op.f('ix_chat_thread_reads_thread_id'), table_name='chat_thread_reads')
    op.drop_table('chat_thread_reads')
    # ### end Alembic commands ###
